# Generated by Django 4.2.30 on 2026-06-03 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Ujian')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('subject', models.CharField(max_length=100, verbose_name='Mata Pelajaran')),
                ('class_target', models.CharField(blank=True, help_text='Kelas yang bisa mengikuti ujian, pisahkan dengan koma', max_length=255, verbose_name='Kelas Target')),
                ('access_mode', models.CharField(choices=[('login_required', 'Login Siswa'), ('guest_allowed', 'Tanpa Login (Guest)'), ('both', 'Keduanya')], default='login_required', max_length=20, verbose_name='Mode Akses')),
                ('exam_code', models.CharField(help_text='Kode unik untuk link publik', max_length=20, unique=True, verbose_name='Kode Ujian')),
                ('public_link_enabled', models.BooleanField(default=False, verbose_name='Link Publik Aktif')),
                ('require_exam_token', models.BooleanField(default=False, verbose_name='Memerlukan Token Ujian')),
                ('exam_token', models.CharField(blank=True, max_length=50, verbose_name='Token Ujian')),
                ('guest_allow_retake', models.BooleanField(default=False, verbose_name='Guest Boleh Mengulang')),
                ('guest_prevent_duplicate_by_nis', models.BooleanField(default=True, verbose_name='Cegah Duplikat NIS')),
                ('guest_prevent_duplicate_by_nisn', models.BooleanField(default=False, verbose_name='Cegah Duplikat NISN')),
                ('guest_prevent_duplicate_by_email', models.BooleanField(default=False, verbose_name='Cegah Duplikat Email')),
                ('guest_prevent_duplicate_by_name_class', models.BooleanField(default=False, verbose_name='Cegah Duplikat Nama+Kelas')),
                ('guest_prevent_duplicate_by_ip', models.BooleanField(default=False, verbose_name='Cegah Duplikat IP')),
                ('start_time', models.DateTimeField(verbose_name='Waktu Mulai')),
                ('end_time', models.DateTimeField(verbose_name='Waktu Selesai')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Durasi (menit)')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Acak Soal')),
                ('shuffle_answers', models.BooleanField(default=False, verbose_name='Acak Jawaban')),
                ('show_result', models.BooleanField(default=True, verbose_name='Tampilkan Hasil')),
                ('max_violations', models.PositiveIntegerField(default=3, verbose_name='Maksimal Pelanggaran')),
                ('passing_score', models.DecimalField(decimal_places=2, default=70, max_digits=5, verbose_name='Nilai Minimal Lulus')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Guru')),
            ],
            options={
                'verbose_name': 'Ujian',
                'verbose_name_plural': 'Ujian',
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Teks Soal')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('essay', 'Essay')], default='multiple_choice', max_length=20, verbose_name='Tipe Soal')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Poin')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Gambar')),
                ('explanation', models.TextField(blank=True, verbose_name='Pembahasan')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Soal',
                'verbose_name_plural': 'Soal',
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('nis', models.CharField(max_length=50, verbose_name='NIS')),
                ('nisn', models.CharField(blank=True, max_length=50, verbose_name='NISN')),
                ('class_name', models.CharField(max_length=50, verbose_name='Kelas')),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor HP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('token_used', models.CharField(blank=True, max_length=50, verbose_name='Token Digunakan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Alamat IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('access_token', models.CharField(help_text='Token sementara untuk mengakses sesi ujian', max_length=255, unique=True, verbose_name='Token Akses')),
                ('token_expires_at', models.DateTimeField(verbose_name='Token Kadaluarsa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_participants', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Peserta Guest',
                'verbose_name_plural': 'Peserta Guest',
                'db_table': 'guest_participants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Mulai')),
                ('end_time', models.DateTimeField(verbose_name='Batas Waktu')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Submit')),
                ('status', models.CharField(choices=[('in_progress', 'Sedang Berlangsung'), ('submitted', 'Telah Dikumpulkan'), ('timed_out', 'Waktu Habis'), ('terminated', 'Dihentikan')], default='in_progress', max_length=20, verbose_name='Status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai')),
                ('violation_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Pelanggaran')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Alamat IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam')),
                ('guest_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='exams.guestparticipant', verbose_name='Peserta Guest')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Siswa (Login)')),
            ],
            options={
                'verbose_name': 'Sesi Ujian',
                'verbose_name_plural': 'Sesi Ujian',
                'db_table': 'exam_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='Teks Pilihan')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Jawaban Benar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question')),
            ],
            options={
                'verbose_name': 'Pilihan Jawaban',
                'verbose_name_plural': 'Pilihan Jawaban',
                'db_table': 'answer_choices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_answer', models.TextField(blank=True, verbose_name='Jawaban Essay')),
                ('is_correct', models.BooleanField(null=True, verbose_name='Benar')),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Poin Didapat')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.answerchoice', verbose_name='Pilihan Jawaban')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession')),
            ],
            options={
                'verbose_name': 'Jawaban Siswa',
                'verbose_name_plural': 'Jawaban Siswa',
                'db_table': 'student_answers',
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.CheckConstraint(check=models.Q(('guest_participant__isnull', True), ('student__isnull', True), _negated=True), name='session_must_have_participant'),
        ),
    ]
