# Generated by Django 4.2.30 on 2026-06-03 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback AI'),
        ),
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('9router', '9Router (lokal)'), ('openrouter', 'OpenRouter'), ('openai', 'OpenAI'), ('custom', 'Custom (OpenAI-compatible)')], default='custom', max_length=50, verbose_name='Provider')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktifkan AI')),
                ('base_url', models.CharField(blank=True, default='https://api.xiaomimimo.com/v1', max_length=255, verbose_name='Base URL')),
                ('model_name', models.CharField(blank=True, default='mimo-v2.5-pro', max_length=100, verbose_name='Model')),
                ('timeout', models.PositiveIntegerField(default=120, verbose_name='Timeout (detik)')),
                ('temperature', models.FloatField(default=0.4, verbose_name='Temperature')),
                ('max_tokens', models.PositiveIntegerField(default=8000, verbose_name='Max Tokens')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Dicek')),
                ('last_status', models.TextField(blank=True, verbose_name='Status Terakhir')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_settings_updated', to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh')),
            ],
            options={
                'verbose_name': 'Pengaturan AI',
                'verbose_name_plural': 'Pengaturan AI',
                'db_table': 'ai_settings',
            },
        ),
    ]
