# Generated by Django 4.2.30 on 2026-06-04 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_studentanswer_ai_feedback_aisetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='guest_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='exams.guestparticipant', verbose_name='Peserta Guest'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Siswa (Login)'),
        ),
    ]
